FROM node:lts as a
COPY . /app
WORKDIR /app
RUN yarn 

FROM a as postgraphile
CMD yarn start-postgraphile

FROM a as api
CMD yarn start-api

FROM a as gateway
CMD yarn start-gateway

FROM a as db-migrator 
CMD yarn db-migrate-up

FROM a as custom-domain-config
CMD yarn start-custom-domain-config