version: '2'
services:
  postgraphile:
    build:
      context: .
      dockerfile: Dockerfile
      target: postgraphile
    network_mode: bridge
    container_name: postgraphile-container
    ports:
      - "5001:80"
    command: "npm run start"
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: gateway